version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
